# Generated by Django 3.1.5 on 2021-01-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='NAME')),
                ('code', models.IntegerField(blank=True, verbose_name='CODE')),
                ('price', models.IntegerField(blank=True, verbose_name='PRICE')),
                ('max_price', models.IntegerField(blank=True, verbose_name='MAX_PRICE')),
                ('min_price', models.IntegerField(blank=True, verbose_name='MIN_PRICE')),
                ('saved_time', models.DateTimeField(auto_now_add=True, verbose_name='SAVED_TIME')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'db_table': 'stock',
                'ordering': ('-saved_time',),
            },
        ),
    ]
