# Generated by Django 3.1.5 on 2021-01-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.TextField(blank=True, verbose_name='PRICE'),
        ),
    ]
