# Generated by Django 3.1.5 on 2021-01-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210129_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='MAX_PRICE'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='MIN_PRICE'),
        ),
    ]
