# Generated by Django 3.1.5 on 2021-01-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='CITY')),
                ('date', models.TextField(verbose_name='DATE')),
                ('desc', models.TextField(verbose_name='DESC')),
                ('temp_min', models.TextField(verbose_name='TEMP_MIN')),
                ('temp_max', models.TextField(verbose_name='TEMP_MAX')),
                ('humidity', models.TextField(verbose_name='HUMIDITY')),
                ('pressure', models.TextField(verbose_name='PRESSURE')),
                ('deg', models.TextField(verbose_name='DEG')),
                ('speed', models.TextField(verbose_name='SPEED')),
            ],
            options={
                'verbose_name': 'weather',
                'verbose_name_plural': 'weathers',
                'db_table': 'weather',
                'ordering': ('date',),
            },
        ),
    ]
