# Generated by Django 3.1.5 on 2021-01-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='realWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='CITY')),
                ('date', models.TextField(verbose_name='DATE')),
                ('desc', models.TextField(verbose_name='DESC')),
                ('temp_min', models.TextField(verbose_name='TEMP_MIN')),
                ('temp_max', models.TextField(verbose_name='TEMP_MAX')),
                ('humidity', models.TextField(verbose_name='HUMIDITY')),
                ('pressure', models.TextField(verbose_name='PRESSURE')),
                ('deg', models.TextField(verbose_name='DEG')),
                ('speed', models.TextField(verbose_name='SPEED')),
            ],
            options={
                'db_table': 'real_weather',
                'ordering': ('date',),
            },
        ),
        migrations.RenameModel(
            old_name='Weather',
            new_name='expectedWeather',
        ),
        migrations.AlterModelOptions(
            name='expectedweather',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelTable(
            name='expectedweather',
            table='expected_weather',
        ),
    ]
