# Generated by Django 3.1.5 on 2021-01-29 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210129_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='realWeather',
            new_name='Weather',
        ),
        migrations.DeleteModel(
            name='expectedWeather',
        ),
        migrations.AlterModelTable(
            name='weather',
            table='weather',
        ),
    ]
